
#
# This file is the default set of rules to compile a Pebble project.
#
# Feel free to customize this to your needs.
#

import os.path
from shutil import copyfile

top = '.'
out = 'build'

ada_libs = ["ada/lib/libada_Patris.a",
            "../Patris_Common/lib/libPatris_Common.a",
            "../../pebble-binding/lib/libPebble_Binding.a"]

def copy_ada_libs():
    for lib in ada_libs:
        copyfile (lib,
                  os.path.splitext(lib)[0]+".o")

def ada_objs_list():
    return map(lambda lib_name: os.path.splitext(lib_name)[0]+".o", ada_libs)

def options(ctx):
    ctx.load('pebble_sdk')

def configure(ctx):
    ctx.load('pebble_sdk')

def build(ctx):
    ctx.load('pebble_sdk')

    build_worker = os.path.exists('worker_src')
    binaries = []

    for p in ctx.env.TARGET_PLATFORMS:
        ctx.set_env(ctx.all_envs[p])
        ctx.set_group(ctx.env.PLATFORM_NAME)
        app_elf='{}/pebble-app.elf'.format(ctx.env.BUILD_DIR)

        copy_ada_libs()

        ctx.pbl_program(source=ctx.path.ant_glob('src/**/*.c') + \
                        ada_objs_list(),
                        target=app_elf)

        if build_worker:
            worker_elf='{}/pebble-worker.elf'.format(ctx.env.BUILD_DIR)
            binaries.append({'platform': p, 'app_elf': app_elf, 'worker_elf': worker_elf})
            ctx.pbl_worker(source=ctx.path.ant_glob('worker_src/**/*.c'),
            target=worker_elf)
        else:
            binaries.append({'platform': p, 'app_elf': app_elf})

    ctx.set_group('bundle')
    ctx.pbl_bundle(binaries=binaries, js=ctx.path.ant_glob('src/js/**/*.js'))
